---
title: "R-Markdown"
author: "Bonsoul"
date: "2025-10-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(pacman)
```

```{r}
pacman::p_load(tidyverse,knitr, kableExtra,tinytex,AER)
```


```{r}
data("CreditCard")

dat <- head(CreditCard)
```

```{r}
dat %>%
  kbl()
```

```{r}
base <- dat %>%
  kbl(align = c(rep("c",7), rep("r",5)), caption = "Example")
base
```

```{r}
base %>%
  kable_styling(bootstrap_options = "striped")

```

```{r}
base %>%
  kable_styling(bootstrap_options = "bordered")
```

```{r}
base %>%
  kable_styling(bootstrap_options = "condensed")
```


```{r}
base %>%
  kable_styling(bootstrap_options = "responsive")
```


```{r}
base %>%
  kable_styling(bootstrap_options = c("bordered","condensed", "responsive", "striped", "hover"))
  
```


```{r}
base %>%
  kable_classic()
```

```{r}
base %>%
  kable_classic_2("hover")
```

```{r}
base %>%
  kable_material("basic", font_size = 12, html_font = "sans")
```

```{r}
base %>%
  kable_material_dark("basic", font_size = 10)
  
```

```{r}
base %>%
  kable_paper("striped", html_font = "helvetica")
```

```{r}
base <- dat %>%
  kable() %>% 
  kable_styling(bootstrap_options = "bordered") %>%
  column_spec(1:ncol(dat), bold = TRUE) %>%
  row_spec(4:6, italic = TRUE, color = "gold", background = "blue")
```



```{r}
base %>%
  kable_styling(bootstrap_options = "bordered") %>%
  column_spec(8:12, bold=T) %>%
  row_spec(4:6, italic = T, color = "gold", background = "blue")
  
  
```

```{r}
base %>%
  kable_styling(bootstrap_options = "bordered") %>%
  pack_rows("Group 1", 3, 5, color = "green") %>%
  pack_rows("Group 2", 6, 6, color="red")
```


```{r}
base %>%
  
  kable_styling(bootstrap_options =  "bordered") %>%
  add_header_above(c("Group 1" = 4, "Group 2" = 2, "Group 3" = 6))
```

```{r}
base %>%
  kable_styling(bootstrap_options =  "bordered") %>%
  column_spec(5, color = spec_color(dat$share[1:6], end = 0.7)) %>%
  column_spec(6, color = "White",
              background = spec_color(dat$expenditure[1:6], begin = 0.3, end = 0.8, option = "C"))
```



